name: CI
on: [pull_request]
jobs:
  run-ci-tests:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v2
      - name: Grant perms
        run: make perms
      - name: Spin up containers
        run: make up
      - name: Run CI test
        run: make ci